# Generated by Django 3.2.5 on 2022-12-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterlog',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('frequency', models.CharField(blank=True, max_length=250)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.enclosure')),
            ],
        ),
    ]
