# Generated by Django 3.2.5 on 2022-12-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20221219_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.diet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
