# Generated by Django 3.2.5 on 2022-12-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20221209_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
