# Generated by Django 3.2.5 on 2022-12-17 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.enclosure')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.parameter')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
